config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  resources :employees
  resources :high_scores
  get 'welcome/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :clients
resources :authors
resources :books
root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    if user.admin?
        can :read, :all
    else
        can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/author.rb
class Author < ApplicationRecord

	has_many :books , dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/client.rb
class Client < ApplicationRecord
	resourcify

	validates :name , :description , :image , presence: true
	validates :name , length: { maximum: 10}
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/high_score.rb
class HighScore < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  
  resourcify
  after_create :assign_default_role

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	def index
		@author = Author.all
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
		@book = Book.all
	end

	def create
		@book = Book.new(params[:book])
		@book= @author.books.create(published_at: Time.now)
		if @book.save
			redirect_to book_path
		else
			render 'new'
		end

	end

	def new
	end

	def destroy
		
		@author.destroy
	end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	
	def index
		@client = Client.all
	end	

	def new
		@client = Client.new
	end
	def show
	end

	def create
		@client = Client.new(params[:client])
		if @client.save
			redirect_to @client
		else
			render 'new'
		end
	end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authors/index.html.erb
this is index page
<table border="1">
<%= @author.each do|f| %>
<tr>
<td>
<%= f.name %>
</td>
</tr>
<% end %>

app/views/books/_form.html.erb
<%= form_tag(controlller:"books" , action:"new" , method:"get") %>
<%= label_tag(:published_at , "published_at") %>

<%#= date_select :published_at %>
<%= date_select :books, :published_at %>


<%= label_tag(:author_id, "Author") %>
<%= text_area_tag(:author_id) %>







<button name="button" type="submit"><a href="show">submit</a></button>

app/views/books/index.html.erb
<p>index page</p>
<%= render 'form' %>

app/views/books/new.html.erb
<%= render 'form' %>

app/views/clients/_form.html.erb
<%= form_tag(controlller:"clients" , action:"new" , method:"get") %>
<%= label_tag(:name , "name") %>
<%= text_field_tag(:name) %>


<%= label_tag(:description , "description") %>
<%= text_area_tag(:description) %>



<%= label_tag(:image , "image") %>
<%= text_field_tag(:image)  %>


<%= check_box_tag(:pet_dog) %>
<%= label_tag(:pet_dog, "I own a dog") %>
<%= check_box_tag(:pet_cat) %>
<%= label_tag(:pet_cat, "I own a cat") %>


<%= radio_button_tag(:age, "child") %>
<%= label_tag(:age_child, "I am younger than 21") %>
<%= radio_button_tag(:age, "adult") %>
<%= label_tag(:age_adult, "I'm over 21") %>

<button name="button" type="submit">submit</button>

app/views/clients/index.html.erb
<p>this is index page</p>
<%= link_to 'new' , new_client_path%>

app/views/clients/new.html.erb
<p>this is new form</p>
<%= render 'form' %>

app/views/clients/show.html.erb
<p>product show</p>
<p><%= @client.name %></p>
<p><%= @client.description %></p>
<p><%= @client.image %></p>